### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by T8mars** [magic-quill/ComfyUI_MagicQuill#1]
![image](https://github.com/user-attachments/assets/50be3301-9a06-469f-b796-4825c502653a)
![image](https://github.com/user-attachments/assets/267f877e-024f-4cce-bb51-8dbe45a6bb91)

hi,how can I do?

**Comment by zliucz** [comment]
Hi :). Please rename the `ComfyUI-BrushNet` folder to `ComfyUI_BrushNet` lol.
