### ISSUE TITLE
!!! Please do not load the model when launching ComfyUI !!!

### ISSUE THREAD

**Issue by wanghkkk** [magic-quill/ComfyUI_MagicQuill#13]
Thank you for your open source, 
but I have a question: 
Is it possible not to load the model when starting ComfyUI, but to wait until the MagicQuill workflow is run to load the required model?

Thanks very much.

**Comment by zliucz** [comment]
Good suggestion. We might update a fix, thanks. For now, just disable magicquill if you are not going to use it.
