### ISSUE TITLE
why?

### ISSUE THREAD

**Issue by cyberdemonz** [magic-quill/ComfyUI_MagicQuill#14]
Error compiling Cython file:
      ------------------------------------------------------------
      ...
                          &self.argkmin_indices[idx, 0],
                          self.k,
                      )
              return

          cdef void compute_exact_distances(self) nogil:
               ^
      ------------------------------------------------------------

      sklearn\metrics\_pairwise_distances_reduction\_argkmin.pyx:775:9: Signature not compatible with previous declaration

**Comment by cyberdemonz** [comment]
This issue happend when install "scikit-learn==1.2.2" .There's many  "Error compiling Cython file" report.

**Comment by zliucz** [comment]
sciklit-learn is required by [comfyui_controlnet_aux](https://github.com/Fannovel16/comfyui_controlnet_aux) extension. You still can use magicquill without this package. Just make sure other requirements are correctly installed.
